### ISSUE TITLE
generic imitation component: naming conventions

### ISSUE THREAD

**Issue by leander-j** [pik-copan/pycopancore#155]
Two methods exist for batch-updating nodes:

- `imi_batch_n` for an absolute number
- `imi_p_in_batch` for a probability for each node.

As with `imi_n_neighbors_drawn` and `imi_p_neighbor_drawn` they could be named in a similar manner, e.g. `imi_x_in_batch`.

**Comment by mensch72** [comment]
I named them so deliberately. "batch" is a singular, so "bath_n" is short for "batch size". "neighbors" is a plural, so "n_neighbors" is short for "number of neighbors".

**Comment by mensch72** [comment]
as commented above.
